CPPFLAGS=$(CPPGLOBAL) /I .. /I ../include /D _MBCS /D _LIB /D _TC_STATIC /FpRelease\LDLib.pch /YX /c


COBJS = 
CCOBJS = \
	$(OBJDIR)\LDLibraryUpdateInfo.obj \
	$(OBJDIR)\LDLibraryUpdater.obj \
	$(OBJDIR)\LDModelParser.obj \
	$(OBJDIR)\LDrawModelViewer.obj \
	$(OBJDIR)\LDPreferences.obj \
	$(OBJDIR)\LDHtmlInventory.obj \
	$(OBJDIR)\LDPartCount.obj \
	$(OBJDIR)\LDPartsList.obj \
	$(OBJDIR)\LDViewPoint.obj

LIBT = LDLib.lib

!include "..\Make.inc"



