#!/bin/bash
input=$1
input=$(printf '%b' "${input//%/\\x}")
input=${input/file:\/\/}
output=$2
size=$3
if [ -f /tmp/ldraw-thumbnailer.log ] ; then
	echo $input $output $size >>/tmp/ldraw-thumbnailer.log
fi
/usr/bin/LDView "$input" -SaveSnapshot=$output.png -CheckPartTracker=0 \
-SaveWidth=$size -SaveHeight=$size -ShowErrors=0 -SaveActualSize=0
if [ -f $output.png ] ; then
	mv -f $output.png $output
fi

