#!/bin/bash
input=$1
output=$2
size=$3
input=`echo $input|sed 's|^file://||g'`
#echo $input $output $size >>/tmp/ldraw-thumbnailer.log
/usr/bin/LDView "$input" -SaveSnapshot=$output.png \
-SaveWidth=$size -SaveHeight=$size -ShowErrors=0 -SaveActualSize=0
cp -f $output.png $output
rm -f $output.png

