CPPFLAGS=$(CPPGLOBAL) /I .. /I ..\include /D _MBCS /D _LIB /D _TC_STATIC /FpRelease\LDExporter.pch /YX /c

COBJS = $(OBJDIR)\LDExporter.obj \
        $(OBJDIR)\LDPovExporter.obj
CCOBJS = 

LIBT = LDExporter.lib

!include "..\Make.inc"

