CPPFLAGS=$(CPPGLOBAL) /I .. /I ..\include /D _MBCS /D _LIB /D _TC_STATIC /Fp$(OBJDIR)\LDExporter.pch /c

COBJS = $(OBJDIR)\LDExporter.obj \
	  $(OBJDIR)\LDExporterSetting.obj \
        $(OBJDIR)\LDPovExporter.obj \
	  $(OBJDIR)\LDStlExporter.obj \
	  $(OBJDIR)\LD3dsExporter.obj
CCOBJS = 

LIBT = LDExporter

!include "..\Make.inc"

