//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by LDView.rc
//
#define IDS_DESCRIPTION                 1
#define IDS_STRING2                     100
#define IDI_ICON1                       101
#define IDI_APP_ICON                    101
#define IDR_MAIN_MENU                   104
#define IDR_ACCELERATORS                105
#define IDD_LDRAWDIR                    106
#define IDD_PREFERENCES                 107
#define IDD_ABOUT_BOX                   108
#define IDD_LOAD_PROGRESS               109
#define IDD_ERRORS                      110
#define IDB_PARSE_ERROR                 111
#define IDB_FNF_ERROR                   112
#define IDB_PARSE                       113
#define IDB_FNF                         115
#define IDB_COLOR                       116
#define IDB_MATCHING_POINTS             116
#define IDB_CONCAVE_QUAD                117
#define IDB_CONCAVE_QUAD_SPLIT          118
#define IDB_OPENGL                      119
#define IDB_DETERMINANT                 120
#define IDB_INFO                        122
#define IDB_PARSE_MASK                  123
#define IDB_CONCAVE_QUAD_MASK           124
#define IDB_COLOR_MASK                  125
#define IDB_MATCHING_POINTS_MASK        125
#define IDB_CONCAVE_QUAD_SPLIT_MASK     126
#define IDB_DETERMINANT_MASK            127
#define IDB_FNF_MASK                    128
#define IDB_INFO_MASK                   129
#define IDB_OPENGL_MASK                 130
#define IDD_SS_SETTINGS                 134
#define IDD_SS_PREFERENCES              135
#define IDB_SS_PREVIEW                  136
#define IDD_GEOMETRY_PREFS              137
#define IDD_EFFECTS_PREFS               138
#define IDD_GENERAL_PREFS               139
#define IDI_WIDE_ICON                   140
#define IDD_SAVE_OPTIONS                141
#define IDD_OPENGL_INFO                 143
#define IDR_STUDLOGO_PNG                147
#define IDR_SANS_FONT                   148
#define IDI_EXAMINE                     149
#define IDI_FLYTHROUGH                  150
#define IDD_NEW_PREF_SET                151
#define IDD_PREFSET_APPLY               152
#define IDD_HOTKEY                      153
#define IDD_EXTRA_DIRS                  155
#define IDB_EXTRA_DIRS                  159
#define IDB_MATRIX                      160
#define IDB_MATRIX_MASK                 161
#define IDR_LOCAL_STRINGS               161
#define IDB_NON_FLAT_QUAD               162
#define IDD_INVISIBLE_COMMANDS          162
#define IDB_NON_FLAT_QUAD_MASK          163
#define IDR_TOOLBAR_MENU                163
#define IDB_COLINEAR                    164
#define IDR_SS_PREVIEW                  164
#define IDB_COLINEAR_MASK               165
#define IDD_LIBRARY_UPDATES             165
#define IDB_VERTEX_ORDER                167
#define IDD_UPDATES_PREFS               167
#define IDB_VERTEX_ORDER_MASK           168
#define IDI_LDRAW                       169
#define IDB_ERROR_LOOP                  169
#define IDI_MPD                         170
#define IDB_ERROR_LOOP_MASK             170
#define IDD_PARTS_LIST                  171
#define IDB_LIGHT_ANGLES                173
#define IDI_LIGHT_ANGLE_UR              174
#define IDR_LIGHT_ANGLE_UR              174
#define IDI_LIGHT_ANGLE_UL              175
#define IDR_LIGHT_ANGLE_UL              175
#define IDI_LIGHT_ANGLE_UM              176
#define IDR_LIGHT_ANGLE_UM              176
#define IDR_LIGHT_ANGLE_MR              177
#define IDR_LIGHT_ANGLE_LL              178
#define IDR_LIGHT_ANGLE_ML              179
#define IDR_LIGHT_ANGLE_MM              180
#define IDR_LIGHT_ANGLE_LM              181
#define IDR_LIGHT_ANGLE_LR              182
#define IDR_EXPORTER_STRINGS            183
#define IDD_JPEG_OPTIONS                183
#define IDD_MODELTREE                   184
#define IDD_TOOLBAR                     185
#define IDD_BOUNDING_BOX                187
#define IDD_LAT_LON                     188
#define IDD_MPD                         189
#define IDD_STEP                        190
#define IDR_TB_ERRORS                   500
#define IDR_TB_EXAMINE                  501
#define IDR_TB_FLYTHROUGH               502
#define IDR_TB_FULLSCREEN               503
#define IDR_TB_OPEN                     504
#define IDR_TB_PREFERENCES              505
#define IDR_TB_RELOAD                   506
#define IDR_TB_SAVE                     507
#define IDR_TB_ZOOMTOFIT                508
#define IDR_TB_FIRST_STEP               509
#define IDR_TB_LAST_STEP                510
#define IDR_TB_NEXT_STEP                511
#define IDR_TB_PREV_STEP                512
#define IDR_TB_HELP                     513
#define IDR_TB_MODELTREE                514
#define IDR_TB_MODELBBOX                515
#define IDR_TB_TOPMOST                  516
#define IDR_TB_VIEW_FRONT               517
#define IDR_TB_VIEW_BACK                518
#define IDR_TB_VIEW_LEFT                519
#define IDR_TB_VIEW_RIGHT               520
#define IDR_TB_VIEW_TOP                 521
#define IDR_TB_VIEW_BOTTOM              522
#define IDR_TB_VIEW_2_3RDS              523
#define IDR_TB_STUD                     524
#define IDR_TB_EXPORT                   525
#define IDR_TB_PRINT                    526
#define IDR_TB_LATLON                   527
#define IDR_TB_LATLONROT                528
#define IDR_TB_MPD                      529
#define IDR_TB_PARTSLIST                530
#define IDR_TB_POVCAMERA                531
#define IDR_TB_RIGHTSIDEUP              532
#define IDR_TB_TEXMAPS                  533
#define IDC_LIGHTING_QUALITY            1001
#define IDC_FRAME_RATE                  1002
#define IDC_HIGHLIGHTS                  1003
#define IDC_TRANS_DEFAULT_COLOR         1004
#define IDC_FLAT_SHADING                1005
#define IDC_RANDOM_COLORS               1006
#define IDC_ALTERNATE_LIGHTING          1007
#define IDC_STIPPLE                     1008
#define IDC_DRAW_LIGHT_DATS             1009
#define IDC_OPTIONAL_STANDARD_LIGHT     1010
#define IDC_HIDE_LIGHT_DAT              1011
#define IDC_STEREO                      1012
#define IDC_ALWAYS_BLACK                1013
#define IDC_CROSS_EYED_STEREO           1014
#define IDC_CURVE_QUALITY               1018
#define IDC_OK                          1019
#define IDC_ANISO_LEVEL                 1019
#define IDC_CURVE_QUALITY_LABEL         1020
#define IDC_BACKGROUND_COLOR            1021
#define IDC_GENERAL_MISC_BOX            1022
#define IDC_DEFAULT_COLOR               1023
#define IDC_SEAM_WIDTH_FIELD            1031
#define IDC_LIGHTING                    1033
#define IDC_WIREFRAME                   1034
#define IDC_WIREFRAME_FOG               1035
#define IDC_QUALITY_LINES               1036
#define IDC_LIGHTING_SUBDUED            1037
#define IDC_LDRAWDIR                    1038
#define IDC_EDGES_ONLY                  1038
#define IDC_ALL_CONDITIONAL             1039
#define IDC_SEAM_SCROLL                 1040
#define IDC_CONDITIONAL_CONTROLS        1040
#define IDC_REMOVE_HIDDEN_LINES         1041
#define IDC_BFC                         1042
#define IDC_CANCEL                      1043
#define IDC_RED_BACK_FACES              1043
#define IDC_APPLY                       1044
#define IDC_GREEN_FRONT_FACES           1044
#define IDC_ABANDON                     1045
#define IDC_BLUE_NEUTRAL_FACES          1045
#define IDC_FS_REFRESH                  1046
#define IDC_FS_RATE                     1047
#define IDC_PROGRESS                    1048
#define IDC_FOV                         1048
#define IDC_LOAD_PROGRESS_MSG           1049
#define IDC_SORT                        1050
#define IDC_ERROR_TREE                  1051
#define IDC_SEAM_SPIN                   1053
#define IDC_SHOW_ERRORS                 1054
#define IDC_PARSE_ERROR                 1055
#define IDC_FILE_NOT_FOUND              1056
#define IDC_PART_DETERMINANT            1057
#define IDC_CONCAVE_QUAD                1058
#define IDC_CONCAVE_QUAD_SPLIT          1059
#define IDC_OPENGL_ERROR                1060
#define IDC_COLOR_ERROR                 1061
#define IDC_COLINEAR_POINTS             1062
#define IDC_COPY_ERROR                  1063
#define IDC_FILENAME_FIELD              1064
#define IDC_SS_FILENAME_FIELD           1064
#define IDC_BROWSE_BUTTON               1065
#define IDC_SS_BROWSE_FILE_BUTTON       1065
#define IDC_SIZE_SLIDER                 1066
#define IDC_SS_SIZE_SLIDER              1066
#define IDC_SS_DIRECTORY_FIELD          1067
#define IDC_SS_BROWSE_DIR_BUTTON        1068
#define IDC_SPEED_SLIDER                1069
#define IDC_SS_SPEED_SLIDER             1069
#define IDC_PARALLEL_STEREO             1071
#define IDC_ROTATION_SPEED_SLIDER       1072
#define IDC_SS_ROTATION_SPEED_SLIDER    1072
#define IDC_STEREO_SPACING              1073
#define IDC_STEREO_SPACING_LABEL        1074
#define IDC_EDGE_THICKNESS              1075
#define IDC_WIREFRAME_THICKNESS         1076
#define IDC_WIREFRAME_THICKNESS_LABEL   1077
#define IDC_EDGE_THICKNESS_LABEL        1078
#define IDC_PRINT_PRINTER_DPI           1079
#define IDC_PRINT_SPECIFY_DPI           1080
#define IDC_BACKGROUND_COLOR_LABEL      1081
#define IDC_DEFAULT_COLOR_LABEL         1082
#define IDC_TRANSPARENCY_BOX            1084
#define IDC_EFFECTS_MISC_BOX            1085
#define IDC_SAVE_ACTUAL_SIZE            1086
#define IDC_SAVE_WIDTH                  1087
#define IDC_SAVE_WIDTH_LABEL            1088
#define IDC_SAVE_HEIGHT                 1089
#define IDC_SAVE_HEIGHT_LABEL           1090
#define IDC_SAVE_DIGITS                 1091
#define IDC_SAVE_SERIES                 1092
#define IDC_SAVE_DIGITS_SPIN            1093
#define IDC_SAVE_DIGITS_LABEL           1094
#define IDC_PRINT_DPI                   1103
#define IDC_TEXTURE_NEAREST             1109
#define IDC_TEXTURE_BILINEAR            1110
#define IDC_TEXTURE_TRILINEAR           1111
#define IDC_PRIMITIVES_BOX              1112
#define IDC_MISSING_PARTS_BOX           1113
#define IDC_AA_BOX                      1114
#define IDC_WIREFRAME_BOX               1115
#define IDC_EDGES_BOX                   1116
#define IDC_LIGHTING_BOX                1117
#define IDC_STEREO_BOX                  1118
#define IDC_CUTAWAY_BOX                 1119
#define IDC_CUTAWAY_COLOR               1120
#define IDC_CUTAWAY_MONOCHROME          1121
#define IDC_CUTAWAY_OPACITY             1122
#define IDC_CUTAWAY                     1123
#define IDC_CUTAWAY_OPACITY_LABEL       1124
#define IDC_CUTAWAY_THICKNESS_LABEL     1125
#define IDC_CUTAWAY_THICKNESS           1126
#define IDC_SS_RESET                    1128
#define IDC_GENERAL_RESET               1129
#define IDC_EFFECTS_RESET               1130
#define IDC_GEOMETRY_RESET              1131
#define IDC_PRIMITIVES_RESET            1132
#define IDC_SMOOTH_CURVES               1134
#define IDC_OPENGL_INFO                 1136
#define IDC_LINE_AA                     1137
#define IDC_NEW_PREF_SET                1142
#define IDC_DELETE_PREF_SET             1143
#define IDC_PREFSETS_LIST               1144
#define IDC_NEW_PREF_SET_FIELD          1145
#define IDC_PREF_SET_HOT_KEY            1145
#define IDC_NEW_PREF_SET_OK             1146
#define IDC_NEW_PREF_SET_CANCEL         1147
#define IDC_PREFSETS_LABEL              1149
#define IDC_HOTKEY_COMBO                1150
#define IDC_HOTKEY_OK                   1151
#define IDC_FSAA_COMBO                  1152
#define IDC_FSAA_LABEL                  1153
#define IDC_FOV_LABEL                   1154
#define IDC_FOV_RANGE_LABEL             1155
#define IDC_COLORS_BOX                  1156
#define IDC_MEMORY_LABEL                1157
#define IDC_SAVE_ZOOMTOFIT              1158
#define IDC_ESD_TOOLBAR                 1159
#define IDC_STEP_TOOLBAR                1160
#define IDC_ESD_LIST                    1163
#define IDC_SS_SIZE_BOX                 1164
#define IDC_SS_SPEED_BOX                1165
#define IDC_SS_ROTATION_SPEED_BOX       1166
#define IDC_SS_SLEEP                    1168
#define IDC_SS_FILENAME_RADIO           1169
#define IDC_SS_DIRECTORY_RADIO          1170
#define IDC_SS_RANDOM_PREF_SET          1171
#define IDC_VERSION_LABEL               1172
#define IDC_SHOW_WARNINGS               1174
#define IDC_ERROR_LIST                  1180
#define IDC_ERROR_SHOW_ALL              1181
#define IDC_ERROR_SHOW_NONE             1182
#define IDC_BFC_BOX                     1184
#define ID_VIEWANGLE                    1189
#define ID_TOOLBAR                      1190
#define IDC_IGNORE_PBUFFER              1190
#define ID_STATUS_BAR                   1191
#define IDC_SAVE_SERIES_BOX             1191
#define IDC_MISC_BOX                    1192
#define IDC_SAVE_ACTUAL_SIZE_BOX        1193
#define IDC_MEMORY_COMBO                1194
#define IDC_UPDATE_PROGRESS             1195
#define IDC_UPDATE_STATUS_FIELD         1196
#define IDC_UPDATES_RESET               1197
#define IDC_PROXY_NONE                  1199
#define IDC_PROXY_WINDOWS               1200
#define IDC_PROXY_MANUAL                1201
#define IDC_PROXY_SERVER                1202
#define IDC_PROXY_PORT                  1203
#define IDC_CHECK_PART_TRACKER          1204
#define IDC_PROXY_SERVER_LABEL          1205
#define IDC_PROXY_PORT_LABEL            1206
#define IDC_PROXY_BOX                   1207
#define IDC_UPDATES_NOTE                1208
#define IDC_MISSING_DAYS_LABEL          1209
#define IDC_UPDATED_DAYS_LABEL          1210
#define IDC_COLUMN_ORDER_LIST           1210
#define IDC_MISSING_DAYS                1211
#define IDC_UPDATED_DAYS                1212
#define IDC_SHOW_MODEL                  1213
#define IDC_EXTERNAL_CSS                1214
#define IDC_SHOW_PART_IMAGES            1215
#define IDC_TOOLBAR                     1216
#define IDC_SHOW_FILE                   1217
#define IDC_LIGHT_UL                    1217
#define IDC_LIGHT_UM                    1218
#define IDC_LIGHT_UR                    1219
#define IDC_LIGHT_ML                    1220
#define IDC_LIGHT_MM                    1221
#define IDC_LIGHT_MR                    1222
#define IDC_LIGHT_LL                    1223
#define IDC_LIGHT_LM                    1224
#define IDC_LIGHT_LR                    1225
#define IDC_LIGHT_DIR                   1226
#define IDC_UL                          1231
#define IDC_UM                          1232
#define IDC_ANISO_LEVEL_LABEL           1232
#define IDC_UR                          1233
#define IDC_SAVE_OPTIONS                1233
#define IDC_JPEG_QUAL_SLIDER            1234
#define IDC_JPEG_QUAL_FIELD             1235
#define IDC_JPEG_QUAL_SPIN              1236
#define IDC_JPEG_SUBSAMPLING_COMBO      1237
#define IDC_JPEG_PROGRESSIVE_CHECK      1238
#define IDC_MODEL_TREE                  1239
#define IDC_OPTIONS                     1240
#define IDC_COMMENT                     1241
#define IDC_MODEL                       1242
#define IDC_LINE                        1243
#define IDC_TRIANGLE                    1244
#define IDC_QUAD                        1245
#define IDC_CONDITIONAL                 1246
#define IDC_EMPTY                       1247
#define IDC_UNKNOWN                     1248
#define IDC_SHOW_BOX                    1249
#define IDC_STEP                        1250
#define IDC_STEP_LABEL                  1251
#define IDC_NUM_STEPS                   1252
#define IDC_TRANSPARENT_BACKGROUND      1253
#define IDC_AUTO_CROP                   1254
#define IDC_ALL_STEPS                   1255
#define IDC_STEP_SUFFIX                 1256
#define IDC_SAME_SCALE                  1257
#define IDC_STEP_SUFFIX_LABEL           1258
#define IDC_ALL_STEPS_BOX               1259
#define IDC_SHOW_AXES                   1260
#define IDC_SNAPSHOTS_DIR_COMBO         1261
#define IDC_PARTS_LIST_DIR_COMBO        1262
#define IDC_SNAPSHOTS_DIR               1263
#define IDC_BROWSE_SNAPSHOTS_DIR        1264
#define IDC_PARTS_LIST_DIR              1265
#define IDC_BROWSE_PARTS_LIST_DIR       1266
#define IDC_SNAPSHOTS_DIR_BOX           1267
#define IDC_SAVE_DIRS_BOX               1267
#define IDC_PARTS_LIST_DIR_BOX          1268
#define IDC_EXPORT_DIR_COMBO            1268
#define IDC_MIN_POINT                   1269
#define IDC_EXPORT_DIR                  1269
#define IDC_MAX_POINT                   1270
#define IDC_LATITUDE                    1270
#define IDC_BROWSE_EXPORT_DIR           1270
#define IDC_LONGITUDE                   1271
#define IDC_MPD_LIST                    1272
#define IDC_DISTANCE                    1272
#define IDC_PART_BOUNDING_BOXES         1273
#define IDC_OPTIONS_CANVAS              1278
#define IDC_RESIZEGRIP                  1279
#define IDC_STEP_FIELD                  1281
#define IDC_RESET                       1282
#define IDC_DISTANCE_CHECK              1283
#define IDC_DEFAULT                     1284
#define IDC_CURRENT                     1285
#define IDC_HIGHLIGHT                   1286
#define IDC_PRINT_BACKGROUND            1287
#define IDC_HIGHLIGHT_COLOR             1287
#define IDC_OVERWRITE                   1288
#define IDC_TEXMAPS                     1289
#define IDC_CONDITIONAL_HIGHLIGHTS      1290
#define IDC_HI_RES                      1291
#define IDC_MODEL_BOX                   1292
#define IDC_PRIMITIVE_SUBSTITUTION      1293
#define IDC_PRIMITIVES_MISC_BOX         1294
#define IDC_PROCESS_LDCONFIG            1295
#define IDC_SEAMS                       1296
#define IDC_SPECULAR                    1297
#define IDC_STUD_QUALITY                1298
#define IDC_TEXTURE_ANISO               1299
#define IDC_TEXTURE_STUDS               1300
#define IDC_TRANSPARENT_TEXTURES_LAST   1301
#define IDC_TEXTURE_OFFSET              1302
#define IDC_TEXTURE_OFFSET_LABEL        1303
#define PRINTDLGORD                     1538
#define PAGESETUPDLGORD                 1546
#define IDD_PRIMITIVES_PREFS            1547
#define IDD_PREFSETS_PREFS              1548
#define IDD_EXPORT_SAVE_OPTIONS         1549
#define IDD_EXPORT_OPTIONS              1550
#define IDD_OPTIONS_CANVAS              1551
#define IDD_OPTIONS_SCROLLER            1552
#define ID_HELP_ABOUT                   40003
#define ID_FILE_EXIT                    40004
#define ID_EDIT_PREFERENCES             40005
#define ID_VIEW_FULLSCREEN              40013
#define ID_FILE_POLLING_DISABLED        40017
#define ID_FILE_POLLING_PROMPT          40018
#define ID_FILE_POLLING_AUTO            40019
#define ID_FILE_POLLING_BACKGROUND      40020
#define ID_FILE_RELOAD                  40021
#define ID_HELP_CONTENTS                40023
#define ID_VIEW_RESET                   40025
#define ID_TOOLS_ERRORS                 40026
#define ID_FILE_PAGESETUP               40032
#define ID_HELP_OPENGLINFO_WGLEXTENSIONS 40033
#define ID_HELP_OPENGL_INFO             40035
#define ID_VIEW_FLYTHROUGH              40037
#define ID_VIEW_EXAMINE                 40038
#define ID_FILE_LDRAWDIR                40039
#define ID_VIEW_STATUSBAR               40040
#define ID_FILE_CANCELLOAD              40041
#define ID_VIEW_ALWAYSONTOP             40043
#define ID_HOT_KEY_0                    40044
#define ID_HOT_KEY_1                    40045
#define ID_HOT_KEY_2                    40046
#define ID_HOT_KEY_3                    40047
#define ID_HOT_KEY_4                    40048
#define ID_HOT_KEY_5                    40049
#define ID_HOT_KEY_6                    40050
#define ID_HOT_KEY_7                    40051
#define ID_HOT_KEY_8                    40052
#define ID_HOT_KEY_9                    40053
#define ID_VIEW_DEFAULT                 40054
#define ID_VIEW_FRONT                   40055
#define ID_VIEW_BACK                    40056
#define ID_VIEW_LEFT                    40057
#define ID_VIEW_RIGHT                   40058
#define ID_VIEW_TOP                     40059
#define ID_VIEW_BOTTOM                  40060
#define ID_TOOLS_VIEW_INFO              40061
#define ID_VIEW_ISO                     40063
#define ID_VIEW_SAVE_DEFAULT            40064
#define ID_VIEW_ZOOMTOFIT               40065
#define ID_FILE_EXTRADIRS               40068
#define ID_FILE_CHECKFORLIBUPDATES      40070
#define ID_EDGES_SHOWEDGESONLY          40071
#define ID_EDGES_CONDITIONALLINES       40072
#define ID_EDGES_HIGHQUALITY            40073
#define ID_EDGES_ALWAYSBLACK            40074
#define ID_VIEW_VISUALSTYLE             40075
#define ID_WIREFRAME_FOG                40076
#define ID_WIREFRAME_REMOVEHIDDENLINES  40077
#define ID_PRIMITIVES_TEXTURESTUDS      40079
#define ID_LIGHTING_HIGHQUALITY         40080
#define ID_LIGHTING_SUBDUED             40081
#define ID_LIGHTING_SPECULARHIGHLIGHT   40082
#define ID_LIGHTING_ALTERNATESETUP      40083
#define ID_BFC_REDBACKFACES             40084
#define ID_BFC_GREENFRONTFACES          40085
#define ID_TOOLS_POV_CAMERA             40087
#define ID_TOOLS_PARTSLIST              40088
#define ID_LIGHTING_DRAWDATS            40089
#define ID_LIGHTING_OPTIONALMAIN        40090
#define ID_VIEW_EXAMINE_LAT_LONG        40091
#define ID_TOOLS_MODELTREE              40092
#define ID_NEXT_STEP                    40093
#define ID_PREV_STEP                    40094
#define ID_FIRST_STEP                   40095
#define ID_LAST_STEP                    40096
#define ID_TOOLS_BOUNDINGBOX            40097
#define ID_VIEW_SPECIFYLATLON           40099
#define ID_TOOLS_MPD                    40100
#define ID_FILE_EXPORT                  40101
#define ID_VIEW_STANDARDSIZES_DUMMYITEM 40103
#define ID_TOOLS_POV_CAMERA_ASPECT      40104
#define ID_GOTO_STEP                    40109
#define ID_TBCONTEXT_CUSTOMIZE          40110
#define ID_TBCONTEXT_MAIN               40111
#define ID_TBCONTEXT_STEPS              40113
#define ID_BFC_BLUENEUTRALFACES         40114
#define ID_VIEW_FLATTENHORIZON          40115
#define ID_VIEW_RIGHTSIDEUP             40115
#define ID_VIEW_KEEPRIGHTSIDEUP         40116
#define ID_PRIMITIVES_TEXMAPS           40117
#define ID_FILE_OPEN                    0xE101
#define ID_FILE_SAVE                    0xE103
#define ID_FILE_PRINT                   0xE107
#define ID_VIEW_TOOLBAR                 0xE800

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        191
#define _APS_NEXT_COMMAND_VALUE         40118
#define _APS_NEXT_CONTROL_VALUE         1304
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
