FROM archlinux/base
MAINTAINER Peter Bartfai pbartfai@stardust.hu

ADD install-devel-packages.sh /
RUN ./install-devel-packages.sh
VOLUME /mnt/lego
CMD cd ldview/QT ; \
	git pull;  \
	chmod o+w -R .. ;\
	sed -i '/qt4/s/^depends/#depends/' PKGBUILD ;\
	sed -i '/qt5/s/^#depends/depends/' PKGBUILD ;\
	sudo -u nobody makepkg -ef
