FROM ubuntu:16.10 
MAINTAINER Peter Bartfai pbartfai@stardust.hu

RUN apt-get update ; apt-get install -y gcc git make g++ libqt4-dev libpng-dev libjpeg-dev libtinyxml-dev cmake kdelibs5-dev fakeroot lintian libgl2ps-dev build-essential debhelper libosmesa6-dev ccache
RUN git clone https://github.com/tcobbs/ldview
VOLUME /mnt/lego
CMD cd ldview/QT ; git pull; ./makedeb ; if [ -d /mnt/lego ] ; then cp -f ldview*.deb /mnt/lego/ ; fi
