FROM ubuntu:latest
MAINTAINER Peter Bartfai pbartfai@stardust.hu

ARG LDVIEW_BRANCH=master
ENV DEBIAN_FRONTEND=noninteractive
ADD install-devel-packages.sh /
RUN ./install-devel-packages.sh

VOLUME /mnt/lego
CMD cd ldview/QT ; \
	git pull; \
	./makedeb -qt5
