FROM ubuntu:19.04
MAINTAINER Peter Bartfai pbartfai@stardust.hu

ADD install-devel-pacages.sh /
RUN ./install-devel-pacages.sh

VOLUME /mnt/lego
CMD cd ldview/QT ; \
	git pull; \
	./makedeb -qt5 ; \
	if [ -d /mnt/lego ] ; then \
		cp -f ldview*.deb /mnt/lego/ ; \
	fi
