FROM centos:7
MAINTAINER Peter Bartfai pbartfai@stardust.hu

ADD install-devel-packages.sh /
RUN ./install-devel-packages.sh
VOLUME /mnt/lego
CMD yum update -x kernel* -y; \
	cd ldview/QT ; \
	git pull; \
	./makerpm
