FROM archlinux
#MAINTAINER Peter Bartfai pbartfai@stardust.hu

ARG LDVIEW_BRANCH=master
ADD install-devel-packages.sh /
RUN ./install-devel-packages.sh
VOLUME /mnt/lego
CMD cd ldview/QT ; \
	git pull							;\
	chmod o+w -R .. 					;\
	sudo -u nobody makepkg -ef 			;\
	cp -f ldview*pkg.tar.* /mnt/lego
