#!/bin/sh
set -e
update-mime-database  /usr/share/mime >/dev/null
update-desktop-database
gconf-schemas --register ldraw.schemas
#cd /usr/share/gconf/schemas
#GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` \
#gconftool-2 --makefile-install-rule ldraw.schemas >/dev/null
#kill -HUP `pidof nautilus`

#DEBHELPER#
