EXECS= libTCFoundation$(POSTFIX).a
CFLAGSLOC = -O3 -DUNZIP_CMD
LIBDIRS = -L$(QTDIR)/lib
HOSTLIBS =

-include ../Makefile.inc

debug: CFLAGSLOC = -g -DUNZIP_CMD
debug: all

-include .depend
# DO NOT DELETE
