#!/bin/sh
if [ ! -x LDView ] ; then
exit
fi
mkdir -p .obj/LDView4
strip LDView
cp LDView ../8464.mpd ../ChangeHistory.html ../Help.html \
../LDViewMessages.ini ../license.txt ../m6459.ldr ../Readme.txt todo.txt \
ldview_*.qm ../Textures/SansSerif.fnt ../LDExporter/LGEO.xml \
.obj/LDView4/
cp ../Translations/German/LDViewMessages.ini .obj/LDView4/LDViewMessages_de.ini
cp ../Translations/Italian/LDViewMessages.ini .obj/LDView4/LDViewMessages_it.ini
cp ../Translations/Czech/LDViewMessages.ini .obj/LDView4/LDViewMessages_cs.ini
cp ../Translations/Hungarian/LDViewMessages.ini .obj/LDView4/LDViewMessages_hu.ini

cd .obj/LDView4
mv LDViewMessages.ini LDViewMessages_en.ini
cat ../../../LDExporter/LDExportMessages.ini >>LDViewMessages_en.ini
ln -sf LDViewMessages_en.ini LDViewMessages.ini
cd ..
tar cfz ../LDView41.tgz LDView4
rm -rf LDView4
