#!/bin/sh
if [ ! -x LDView ] ; then
exit
fi
mkdir -p .obj/LDView3
strip LDView
cp LDView ../8464.mpd ../ChangeHistory.html ../Help.html \
../LDViewMessages.ini ../license.txt ../m6459.ldr ../Readme.txt todo.txt \
ldview_*.qm \
.obj/LDView3/
cp ../Translations/German/LDViewMessages.ini .obj/LDView3/LDViewMessages_de.ini
cp ../Translations/Italian/LDViewMessages.ini .obj/LDView3/LDViewMessages_it.ini
cp ../Translations/Czech/LDViewMessages.ini .obj/LDView3/LDViewMessages_cz.ini
cp ../Translations/Hungarian/LDViewMessages.ini .obj/LDView3/LDViewMessages_hu.ini

cd .obj/LDView3
mv LDViewMessages.ini LDViewMessages_en.ini
ln -sf LDViewMessages_en.ini LDViewMessages.ini
cd ..
tar cfz ../LDView3.tgz LDView3
rm -rf LDView3
