#! /bin/sh
$QTDIR/bin/qmake
rm -f LDView
if [ -d $QTDIR/include/Qt3Support ] ; then
export TESTING="-DQT3_SUPPORT -I$QTDIR/include/Qt"
fi
make -f LDView.mak all
if [ "$1" = "-s" ]; then
	strip LDView;
fi
