#!/bin/sh
devbuild=.0.1
for pkg in gcc git make g++ libqt4-dev libpng*dev \
	libjpeg*dev libtinyxml-dev cmake kdelibs5-dev fakeroot lintian \
	build-essential libgl2ps-dev debhelper qtbase5-dev qt5-qmake \
	libqt5opengl5-dev libosmesa6-dev ; do
	dpkg-query -W --showformat='${Package;-30}\t${Status}\n' $pkg|\
	grep -qv not-installed
	if [ $? -eq 1 ]  ;then
		echo Missing package: $pkg
	fi
done
if [ -f /etc/lsb-release ] ; then
. /etc/lsb-release
fi
if [ -n "$DISTRIB_ID" ] ; then
	DIST=`echo $DISTRIB_ID|tr '[:upper:]' '[:lower:]'`-$DISTRIB_RELEASE.
else
	if lsb_release -i |grep -q : ; then
		DIST=`lsb_release -is|tr '[:upper:]' '[:lower:]'`-`lsb_release -sc`.
	fi
fi
if (echo  $PATH | grep -q ccache ) ; then
	true
else
	export PATH=/usr/lib/ccache:$PATH
fi
cd ..
ln -sf QT/debian debian
rm -f ../ldview*.dsc ../ldview*.deb QT/ldview*.deb
dpkg-buildpackage
lintian ../ldview*.deb ../ldview*.dsc
rm -f debian
cd ..
if [ -d LDView ] ; then ldvdir=LDView ; 
elif [ -d ldview ] ; then ldvdir=ldview ; fi
cp -f ldview_*.deb $ldvdir/QT/ldview-4.3-${DIST}`dpkg-architecture -qDEB_BUILD_ARCH`.deb
cp -f ldview-osmesa_[1-9].[0-9]*.deb $ldvdir/QT/ldview-osmesa-4.3-${DIST}`dpkg-architecture -qDEB_BUILD_ARCH`.deb
QT_VER=`QT_SELECT=5 qmake -query | grep QT_VERSION | cut -d: -f2|cut -d. -f1`
if [ "$QT_VER" = "5" -a "$1" = "-qt5" ] ; then
	export QT_SELECT=5
	cp -rf $ldvdir/QT/debian $ldvdir/
	cd $ldvdir
	sed -i '/libqt4-dev/d' debian/control
	sed -i '/qtbase5/s/^#//' debian/control
	sed -i '/ldview-osmesa/,+10d' debian/control
	sed -i 's/Package: ldview/Package: ldview-qt5/' debian/control
	sed -i 's/export QT_SELECT=4/export QT_SELECT=5/' debian/rules
	sed -i 's/INSTALL_ROOT=$(DEST) /INSTALL_ROOT=$(DEST)-qt5 /' debian/rules
	sed -i '/osmesa/d' debian/rules
	sed -i '/STATIC/d' debian/rules
	dpkg-buildpackage
	rm -rf debian
	cd ..
	cp -f ldview-qt5_*.deb $ldvdir/QT/ldview-qt5-4.3-${DIST}`dpkg-architecture -qDEB_BUILD_ARCH`.deb
fi

if [ -d /mnt/lego ] ; then
	cp -f ldview*.deb /mnt/lego/
fi

