#!/bin/sh
if [ ! -x LDView ] ; then
exit
fi
mkdir -p .obj/ldview/usr/local/bin
mkdir -p .obj/ldview/usr/local/share/ldview
mkdir -p .obj/ldview/usr/share/applications
mkdir -p .obj/ldview/usr/share/pixmaps
mkdir -p .obj/ldview/usr/share/mime/packages
mkdir -p .obj/ldview/usr/share/mime-info
mkdir -p .obj/ldview/usr/share/application-registry
mkdir -p .obj/ldview/usr/share/icons/gnome/32x32/mimetypes
mkdir -p .obj/ldview/usr/bin
mkdir -p .obj/ldview/usr/share/kd4/services
mkdir -p .obj/ldview/DEBIAN
strip LDView
cp LDView .obj/ldview/usr/local/bin 
cp ../8464.mpd ../ChangeHistory.html ../Help.html \
../LDViewMessages.ini ../license.txt ../m6459.ldr \
../Readme.txt todo.txt ldview_*.qm ../LDExporter/LGEO.xml \
.obj/ldview/usr/local/share/ldview
cp ../Translations/German/LDViewMessages.ini \
.obj/ldview/usr/local/share/ldview/LDViewMessages_de.ini
cp ../Translations/Italian/LDViewMessages.ini \
.obj/ldview/usr/local/share/ldview/LDViewMessages_it.ini
cat ../LDExporter/LDExportMessages.ini >>\
.obj/ldview/usr/local/share/ldview/LDViewMessages.ini
cp images/LDViewIcon48.png .obj/ldview/usr/share/pixmaps/LDView.png
cp ldview.desktop .obj/ldview/usr/share/applications/
cp desktop/ldraw.mime .obj/ldview/usr/share/mime-info/ldraw.mime
cp desktop/ldraw.keys .obj/ldview/usr/share/mime-info/ldraw.keys
cp desktop/ldraw.xml  .obj/ldview/usr/share/mime/packages/ldraw.xml
cp desktop/ldview.applications .obj/ldview/usr/share/application-registry/ldview.applications
cp images/LDViewIcon.png .obj/ldview/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-x-ldraw.png
cp images/LDViewIcon.png .obj/ldview/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-x-multipart-ldraw.png
cp desktop/ldraw-thumbnailer .obj/ldview/usr/bin
cp kde/ldviewthumbnailcreator.desktop \
	.obj/ldview/usr/share/kde4/services/ldviewthumbnailcreator.desktop
cd .obj/ldview/usr/local/share/ldview
mv LDViewMessages.ini LDViewMessages_en.ini
ln -sf LDViewMessages_en.ini LDViewMessages.ini
cd ../../../../..

Arch=`uname -m`
if [ "${Arch}" = "x86_64" ]; then
	InternalArch=amd64
	ExternalArch=x64
else
	InternalArch=i386
	ExternalArch=i386
fi
cat >ldview/DEBIAN/control <<EOF
Package: ldview
Version: 4.1
Priority: optional
Architecture: ${InternalArch}
Section: graphics
Depends: unzip, libqtcore4, libqtgui4, libqt4-opengl
Maintainer: Peter Bartfai <pbartfai@stardust.hu>
Description: Real-time 3D viewer for displaying LDraw models
 LDView is a real-time 3D viewer for displaying LDraw models using hardware-accellerated 3D graphics. It was written using OpenGL, so should be accellerated on any video card which provides full OpenGL 3D accelleration (so-called mini-drivers are not likely to work). It should also work on other video cards using OpenGL software rendering, albeit at a much slower speed. For information on LDraw, please visit www.ldraw.org, the centralized LDraw information site.  The program can read LDraw DAT files as well as MPD files. It then allows you to rotate the model around to any angle with themouse. A fast computer or a video card with T&L support (Transform & Lighting) is strongly recommended for displaying complexmodels.

EOF

find ./ldview -type d | xargs chmod 755
dpkg-deb --build ldview
mv ldview.deb ../ldview-4.1.${ExternalArch}.deb
rm -rf ldview
