#! /bin/sh
sed "s/warn_on debug/warn_on release/" LDView.pro > LDView.release.pro
mv LDView.release.pro LDView.pro
qmake
rm -f LDView
make -f LDView.mak all
if [ "$1" = "-s" ]; then
	strip LDView;
fi
