#!/bin/sh
mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
rpmbuild -bb LDView.spec
for r in /root/rpm*/RPMS/*/ldview*.rpm /usr/src/redhat/RPMS/*/ldview*.rpm /usr/src/packages/RPMS/*/ldview*.rpm ; do
	if [ -f $r ] ; then
		if [ -d /mnt/lego ] ; then
			cp -f $r /mnt/lego
		fi
		rpmlint -f LDView.rpmlintrc $r || true
	fi
done
