name: Build LDView
on: [push, pull_request]
jobs:
  build-ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install OpenGL libraries # <<< NEW STEP ADDED HERE
        run:  sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev
      - name: Install developement packages
        run:  sudo ./QT/docker/install-devel-packages.sh
      - name: Build LDView
        run: cd QT ; ./makedeb -qt5
  
  build-fedora:
    runs-on: ubuntu-22.04
    container:
      image: fedora:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install developement packages
        run:  sudo ./QT/docker/install-devel-packages.sh
      - name: Build LDView
        run:  cd QT ; mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS} ; ./makerpm

  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Build LDView
        shell: cmd
        run: .\build.cmd

  build-windows-2022:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Build LDView
        shell: cmd
        run: .\build.cmd

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build LDView
        run: cd MacOSX/LDView ; xcodebuild
